### PR TITLE
Vast Bronze Salamander - Multiple lzCompose messages did not verify the legality of _srcChainSender #109

### PR DESCRIPTION
**Pull request by cryptotechmaker**
https://github.com/sherlock-audit/2024-02-tapioca-judging/issues/109
https://github.com/sherlock-audit/2024-02-tapioca-judging/issues/140

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dt3u5p2 Vast Bronze Salamander - Multiple lzCompose messages did not verify the legality of _srcChainSender #109](https://app.clickup.com/t/86dt3u5p2)

**Review by maarcweiss — COMMENTED** [review]
Same comment review [than](https://github.com/Tapioca-DAO/Tapioca-bar/pull/377#issuecomment-2086427994) here than in but with the `OFTGenericReceiverModule.sol` module. And seems like `TOFTReceiver.sol` does not need it, but just bringing it into attention

**Comment by 0xRektora** [comment]
Same here https://github.com/Tapioca-DAO/Tapioca-bar/pull/377#issuecomment-2091146688

**Review by maarcweiss — COMMENTED** [review]
Fixed

**Pull request merged**
