### PR TITLE
Gallo(Alex) | to recheck - bin2chen - exerciseOptionsReceiver() Lack of Ownership Check for oTAP, Allowing Anyone to Use oTAPTokenID `CU-86dtj3vm7 `

### PR DESCRIPTION
**Pull request by 0xRektora**
fix(`submodule`): Checked out `periph` to use new `IPearlmit::clearAllowance()`   [`86dtj3vm7`]

fix(`TOFTOptionsReceiverModule`): Updated caller validation + refactored functions   [`86dtj3vm7`]

- Moved `_approve(address(this), address(pearlmit), 0);` from `_exerciseAndRefund()` to `exerciseOptionsReceiver()`
- Replaced `oTap` token owner check with new flow using Pearlmit
- New `_validateExerciseOptionCaller()` to check for `oTap` token owner check
- Clearing allowance after allowance check
- Using `_validateExerciseOptionCaller()`  in `exerciseOptionsReceiver()`

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtj3vm7 Gallo(Alex) | to recheck - bin2chen - exerciseOptionsReceiver() Lack of Ownership Check for oTAP, Allowing Anyone to Use oTAPTokenID #102](https://app.clickup.com/t/86dtj3vm7)

**Comment by 0xRektora** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/212?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#212** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/212?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#208** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#205** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/205?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @0xRektora and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by cryptotechmaker** [comment]
Same comment as on `bar` PR. I don't think `srcChainSender` is used inside the `exerciseAndRefund` method

**Comment by 0xRektora** [comment]
### Merge activity

* **May 23, 6:10 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/212).

**Pull request merged**
