### PR TITLE
Use Pearlmit on TOB exerciseOption for oTAP approval  `CU-86dthzrv6`

### PR DESCRIPTION
**Pull request by 0xRektora**
patch(`TOFTOptionsReceiverModule`): Clear `Pearlmit->oTap` allowance post exercise in `_exerciseAndRefund()`  [`86dthzrv6`]

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtj3vm7 Gallo(Alex) | to recheck - bin2chen - exerciseOptionsReceiver() Lack of Ownership Check for oTAP, Allowing Anyone to Use oTAPTokenID #102](https://app.clickup.com/t/86dtj3vm7)

**Comment by 0xRektora** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/213?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#213** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/213?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#212** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/212?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#207** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#206** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#205** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/205?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @0xRektora and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
Task linked: [CU-86dthzrv6 Use Pearlmit on TOB exerciseOption for oTAP approval](https://app.clickup.com/t/86dthzrv6)

**Comment by cryptotechmaker** [comment]
Not 100% sure. Shouldn't clear allowance from `_options.target` as the operator? 
@0xRektora

**Comment by 0xRektora** [comment]
### Merge activity

* **May 23, 6:10 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/TapiocaZ/213).

**Pull request merged**
